### ISSUE TITLE
Model conversion for multiple models

### ISSUE THREAD

**Issue by pshwetank** [triton-inference-server/model_navigator#2]
Hi Triton team,

Thanks for the model navigator tool and autoconversion, as well as, autovalidation features that comes with it. I wanted to know if there is any way to run it for multiple models. Currently, the commands in documentation only have examples for single model. I want to run it for multiple models that are kept in same folders. I know it is possible by writing a bash script but I was curious if such feature is already there or not. Such feature will completely automate the deployment routine in our case. 

Thanks/

**Comment by pziecina** [comment]
Hi, 

thank you for your kind words. Since the Triton Model Navigator is a relatively new tool, our current focus is on adding other basic features. The functionality mentioned by you is troublesome to be implemented generically (standard vs. custom configuration for each model). Thus it is currently not on our short-term roadmap. We will consider adding support tools in the Triton Model Navigator directory working on bulks of models.
