### ISSUE TITLE
No such file or directory error when model-navigator convert executes 

### ISSUE THREAD

**Issue by justmert** [triton-inference-server/model_navigator#4]
I am trying to convert from Tensorflow saved-model to onnx model, but when I execute model_navigator from command line, this error occurs:

 `FileNotFoundError: [Errno 2] No such file or directory: '/opt/tritonserver/workspace/navigator_workspace/convert_results.yaml`

```
root@my_username:/opt/tritonserver/workspace# model-navigator convert --model-format tf-savedmodel --model-name efficientnetb4  --model-path test_models/tensorflow/saved_models/efficientnetb4 --output-path efficientnetb4.onnx  --override-workspace
2021-08-10 11:04:03 - INFO - model_navigator.utils.docker: Run docker container with image model_navigator_converter:21.05-tf2-py3; using workdir: /opt/tritonserver/workspace
Usage: model-navigator convert [OPTIONS]
Try 'model-navigator convert --help' for help.

Error: Missing option '-n' / '--model-name'.
Traceback (most recent call last):
  File "/usr/local/bin/model-navigator", line 33, in <module>
    sys.exit(load_entry_point('model-navigator', 'console_scripts', 'model-navigator')())
  File "/opt/tritonserver/workspace/model_navigator/model_navigator/cli/main.py", line 49, in main
    cli(max_content_width=160)
  File "/usr/local/lib/python3.8/dist-packages/click/core.py", line 1137, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/click/core.py", line 1062, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.8/dist-packages/click/core.py", line 1668, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.8/dist-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.8/dist-packages/click/core.py", line 763, in invoke
    return __callback(*args, **kwargs)
  File "/opt/tritonserver/workspace/model_navigator/model_navigator/cli/convert_model.py", line 396, in convert_cmd
    return convert(
  File "/opt/tritonserver/workspace/model_navigator/model_navigator/cli/convert_model.py", line 311, in convert
    conversion_results = _run_in_docker(
  File "/opt/tritonserver/workspace/model_navigator/model_navigator/cli/convert_model.py", line 239, in _run_in_docker
    results = results_store.load("convert", ConversionResult)
  File "/opt/tritonserver/workspace/model_navigator/model_navigator/results.py", line 55, in load
    with results_path.open("r") as results_file:
  File "/usr/lib/python3.8/pathlib.py", line 1222, in open
    return io.open(self, mode, buffering, encoding, errors, newline,
  File "/usr/lib/python3.8/pathlib.py", line 1078, in _opener
    return self._accessor.open(self, flags, mode)
FileNotFoundError: [Errno 2] No such file or directory: '/opt/tritonserver/workspace/navigator_workspace/convert_results.yaml'

```

So I can't convert. Is there any solution for this? Thank you.

**Comment by justmert** [comment]
I think the source of the problem is: `The mappings of volumes inside the container must match the host path. This is required to share artifacts between steps correctly, as some steps are executed in separate containers.`

but, is there anything I can do instead of mapping home directory to the container?

**Comment by jkosek** [comment]
Could you provide how the Docker container is started? Just to confirm we deal with the problem you have mentioned.

**Comment by justmert** [comment]
I tried to use model_navigator inside a docker container and that container was not mapping anything. In this case, I couldn't use model_navigator so couldn't try the possible solution that I have suggested yet.

In any case, you need to start the container like the command in [doc](https://github.com/triton-inference-server/model_navigator/blob/main/docs/installation.md#using-docker-container)

```
$ docker run -it \
--gpus 1 \
-v <path-to-model-catalog>:<path-to-model-catalog> \
-v /var/run/docker.sock:/var/run/docker.sock \
-v ${HOME}:${HOME}
-w ${HOME} \
--net host \
--name model-navigator \
model-navigator /bin/bash

root@hostname:/home/{username}#
```

Don't change` -v ${HOME}:${HOME}` and `-v /var/run/docker.sock:/var/run/docker.sock `, and try again. Let's see if this works.

**Comment by jkosek** [comment]
The Navigator container requires additional mappings:
1. `-v /var/run/docker.sock:/var/run/docker.sock` to communicate with host Docker Daemon,
2. `-v /path/to/workdir:/path/to/workdir` -  to create workspace shared between Navigator steps,

In both cases we expect that mapping inside container match the host path. 

For `/var/run/docker.sock` to connect to host Docker Daemon and perform Docker API calls.

For `/path/to/workdir` to create Navigator workspace and share it between other containers which are created in the process.

`Workspace` is a catalog created by Navigator to share artifacts like `convert_results.yaml` generated by executed steps . The path is shared between steps and additional containers created in the process.

When you run Model Navigator container with those mappings:
```
$ docker run -it \
--gpus 1 \
-v /var/run/docker.sock:/var/run/docker.sock \
-v /path/to/workdir:/path/to/workdir \
--net host \
--name model-navigator \
model-navigator /bin/bash
```

You would have two options to run `model-navigator` commands:
1. Go to `/path/to/workdir` and run `model-navigator` command from that directory,
2. Run `model-navigator` with `--workspace-path /path/to/workdir/navigator_workspace` flag,

**Please note** I have dropped here mapping for path where your model is stored just for explanation. In fact you may use `<path-to-model-catalog>` instead of `/path/to/workdir`.

We plan to improve the mapping limitation and will update the documentation to clarify that requirement.
