### ISSUE TITLE
convert_results.yaml instead of convert.yaml?

### ISSUE THREAD

**Issue by dawilliams-nvidia** [triton-inference-server/model_navigator#5]
Following the quick start guide on a fresh install, receive the following error mod:
```
model-navigator run --model-name add_sub \
    --model-path examples/quick-start/model.pt \
    --inputs INPUT__0:-1,16:float32 INPUT__1:-1,16:float32 \
    --outputs OUTPUT__0:-1,16:float32 OUTPUT__1:-1,16:float32 \
    --override-workspace
.
.
.
FileNotFoundError: [Errno 2] No such file or directory: '/workspace/home/navigator_workspace/convert_results.yaml'
```

Investigating the workspace that model navigator creates, I found a "convert.yaml" instead of "convert_results.yaml". I'm unable to just change the file to see if this is the file navigator is looking for that has just been misnamed. Can I get some feedback if these are the same file, or if I have osme other error and it just never gets to the creation of convert_results.yaml?

**Comment by justmert** [comment]
I had the same problem (see: #4) and I think the problem is not directly related to the name of the yaml file.

I think the problem is related to this line in [here](https://github.com/triton-inference-server/model_navigator/blob/main/docs/installation.md#using-docker-container):

> The mappings of volumes inside the container must match the host path. This is required to share artifacts between steps correctly, as some steps are executed in separate containers.

model_navigator executes some commands in separate containers so if any of the containers creates `convert_results.yaml`, there is no way the other container can see that file unless we properly maps the volumes. 

Please check if you have mapped properly.
